//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Step_Test_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int stepheight { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int maxhr { get; set; }
        public string tinit { get; set; }
        public string hrlist { get; set; }
        public decimal aercap { get; set; }
        public string rating { get; set; }
        public int age { get; set; }
        public string remarks { get; set; }
    
        public virtual MP MP { get; set; }
    }
}
